// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDv_RrsrTUqH-WuDFkzBQtyK0YBFC1WTs',
    appId: '1:698582903261:web:abad4aae802a2c1b15ee34',
    messagingSenderId: '698582903261',
    projectId: 'pulsenotes-c8d82',
    authDomain: 'pulsenotes-c8d82.firebaseapp.com',
    storageBucket: 'pulsenotes-c8d82.firebasestorage.app',
    measurementId: 'G-ZYS6WL6N3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx46OodJE18R-TFtroAEf0AY-hlLvMzes',
    appId: '1:698582903261:android:b3204d8a0156628e15ee34',
    messagingSenderId: '698582903261',
    projectId: 'pulsenotes-c8d82',
    storageBucket: 'pulsenotes-c8d82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZSCr7DE_UyzAIuXRVKSjbIXU1TL_mHG4',
    appId: '1:698582903261:ios:7a0f58e5315d6bb715ee34',
    messagingSenderId: '698582903261',
    projectId: 'pulsenotes-c8d82',
    storageBucket: 'pulsenotes-c8d82.firebasestorage.app',
    iosBundleId: 'com.tori.pulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZSCr7DE_UyzAIuXRVKSjbIXU1TL_mHG4',
    appId: '1:698582903261:ios:7a0f58e5315d6bb715ee34',
    messagingSenderId: '698582903261',
    projectId: 'pulsenotes-c8d82',
    storageBucket: 'pulsenotes-c8d82.firebasestorage.app',
    iosBundleId: 'com.tori.pulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDv_RrsrTUqH-WuDFkzBQtyK0YBFC1WTs',
    appId: '1:698582903261:web:35d1e4f601d7074c15ee34',
    messagingSenderId: '698582903261',
    projectId: 'pulsenotes-c8d82',
    authDomain: 'pulsenotes-c8d82.firebaseapp.com',
    storageBucket: 'pulsenotes-c8d82.firebasestorage.app',
    measurementId: 'G-EQH71ZB029',
  );
}
